folder: ./data/bids-rsna-lscd
seqtype: sag-T2
lr: 0.0002 # 0.0001
epochs: 12
val_interval : 1
batch_size: 2
experiment : 1
levels: 
  - l1_l2
  - l2_l3
  - l3_l4
  - l4_l5
  - l5_s1
gpu: cuda:3 #cuda:3
orientation: RSP
pixdim: 
  - 0.6
  - 0.6
  - 4.4
interpmode: bilinear
crop_padd_size: [512, 512, 20] #None
resize : [20, 512, 512]
weights: 
  - 1.0
  - 2.0
  - 4.0
train_size: 0
test_size: 0
val_size: 0
use_amp: "True"
scaler: "True"
exclude_file: ./data/exclude.npy